### ISSUE TITLE
Cookie

### ISSUE THREAD

**Issue by hmert** [academic/gURL#4]
```
 -b, --cookie <data|filename> Send cookies from string/file
 -c, --cookie-jar <filename> Write cookies to <filename> after operation
```

**Comment by gozeloglu** [comment]
You can reference this documentation: https://curl.se/docs/manpage.html

**Comment by hmert** [comment]
it's already ready for me.

https://github.com/academic/gURL/blob/main/src/client.go#L108

**Comment by gozeloglu** [comment]
Yes, I did not notice. Maybe it can be reference for CLI command parsing

**Comment by hmert** [comment]
#11
